site_name: SlopeCraft 文档
docs_dir: 'docs'
repo_url: https://github.com/SlopeCraft/SlopeCraftDocs
repo_name: SlopeCraft/SlopeCraftDocs
edit_uri: edit/main/docs/

site_author: SlopeCraft Team, Cubik65536, ToKiNoBug and Contributors
copyright: Copyright © 2023 SlopeCraft Team, Cubik65536, ToKiNoBug and Contributors. 
  All rights reserved.<br/>
  Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs
    - content.tooltips
  favicon: 'assets/favicon.ico'
  logo: 'assets/logo.png'

# Customization
extra_css:
  - '_static/css/extra.css?v=14'
  
# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - tables
  - footnotes
  - pymdownx.tilde
  - attr_list
  - md_in_html

# Navigation
nav:
  - 欢迎使用 SlopeCraft: index.md
  - 原理简介: principles-introduction.md
  - SlopeCraft 教程: SlopeCraft-tutorial.md
  - VisualCraft 教程: VisualCraft-tutorial.md
  - 常见问题: faq.md
  - 编译指南:
    - 通用: compilation-guide/index.md
    - Windows/Linux: compilation-guide/Windows-Linux.md
    - macOS: compilation-guide/macOS.md

# Plugins
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          name: 中文
          default: true
          site_name: SlopeCraft 文档
          build: true
        - locale: en
          name: English
          site_name: SlopeCraft Documentation
          build: true
          nav_translations:
            欢迎使用 SlopeCraft: Welcome to SlopeCraft
            原理简介: Introduction of Principles
            SlopeCraft 教程: SlopeCraft Tutorial
            VisualCraft 教程: VisualCraft Tutorial
            常见问题: FAQ
            编译指南: Compilation Guide
            通用: General
            Windows/Linux: Windows/Linux
            macOS: macOS

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
